apiVersion: apps/v1
kind: Deployment
metadata:
 name: minecraft-server-teste2
spec:
 replicas: 1
 selector:
   matchLabels:
     app: minecraft-server-teste2
 template:
   metadata:
     labels:
       app: minecraft-server-teste2
   spec:
     containers:
     - name: minecraft-server-teste2
       image: openhack/minecraft-server:2.0
       env:
       - name: EULA
         value: "TRUE"
       volumeMounts:
       - mountPath: /data
         name: server-state
         subPath: minecraft-server-teste2
       ports:
       - containerPort: 25565
         name: game
       - containerPort: 25575
         name: rcon
     volumes:
       - name: server-state
         persistentVolumeClaim:
            claimName: azurefile
---
apiVersion: v1
kind: Service
metadata:
 name: minecraft-server-lb-teste2
spec:
 type: LoadBalancer
 ports:
 - protocol: TCP
   port: 25565
   targetPort: 25565
   name: game
 - protocol: TCP
   port: 25575
   targetPort: 25575
   name: rcon
 selector:
   app: minecraft-server-teste2